services:
  db:
    image: postgres:16
    container_name: qshield-postgres
    environment:
      POSTGRES_USER: qshield
      POSTGRES_PASSWORD: qshield
      POSTGRES_DB: qshield
    ports:
      - "15432:5432"

  redis:
    image: redis:7
    container_name: qshield-redis
    ports:
      - "6379:6379"
